@startuml
hide footbox
title Search API

!include defBuildSearchQuery.def
!include defSearch.def

actor ONSWebsiteUser
autonumber
ONSWebsiteUser -> SearchData : search website
    activate SearchData
    method(SearchData, SearchRequestHelper, extractSearchTerm, searchTerm)

    SearchData -> SearchData : queries
        activate SearchData
        buildSearchQuery(SearchData)
            methodNewReturn(SearchData, ONSQueryBuilders,toList, searchQueries, SearchQueries)
        deactivate SearchData

    search(SearchData,SearchQueries)
    ONSWebsiteUser <-- SearchData : results
    deactivate SearchData

@enduml